### ISSUE TITLE
there are 2 inputs  in ESA's forward

### ISSUE THREAD

**Issue by Feraint** [njulj/RFANet#2]
there are 2 inputs  in ESA's forward (x and f).
if  x is  the output feature map of last layer, then what does f mean?

**Comment by njulj** [comment]
f is the same as x

**Comment by Feraint** [comment]
amazing coding style ……
thanks for replying very soon!

**Comment by njulj** [comment]
I keep this because I have tried other attention mechanism in addition to self attention

**Comment by Feraint** [comment]
now i understand.
looking forward to whole code.
i like this idea. 
non-local based method is awful because of super high computational complexity especially in testing step.

**Comment by njulj** [comment]
Yes. In fact, we also use this block in the AIM20 efficient super-resolution challenge
