### ISSUE TITLE
RFANet网络的参数量是？

### ISSUE THREAD

**Issue by Lininggggggg** [njulj/RFANet#3]
您好，想请问下你们的RFANet网络的参数量是？
我大致算了下，差不多要10M多对吗？

**Comment by njulj** [comment]
是的

--------------原始邮件--------------
发件人："Lininggggggg "<notifications@github.com&gt;;
发送时间：2020年9月25日(星期五) 晚上6:48
收件人："njulj/RFANet" <RFANet@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[njulj/RFANet] RFANet网络的参数量是？ (#3)
-----------------------------------

 

 
您好，想请问下你们的RFANet网络的参数量是？
 我大致算了下，差不多要10M多对吗？

**Comment by Lininggggggg** [comment]
好的，谢谢
